/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Alunos;
import model.Disciplinas;
import mycustom.CustomFrame;
import mycustom.ItemSelection;
import ui.MainFrame;

/**
 *
 * @author thomaz
 */
public class UiAlunoDisciplina extends CustomFrame {

    /**
     * Creates new form UiAlunoDisciplina
     */
    public UiAlunoDisciplina() {
        initComponents();
        
        List<Alunos> alunos = MainFrame.ALUNO_CONTROLLER.findAlunosEntities();
        
        for (Alunos aluno : alunos) {
            jCAlunos.addItem(new ItemSelection<>(aluno));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jCAlunos = new javax.swing.JComboBox();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        jLDisciplinas = new javax.swing.JList();
        javax.swing.JButton jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Aluno");

        jCAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCAlunosActionPerformed(evt);
            }
        });

        jLabel2.setText("Disciplinas");

        jScrollPane1.setViewportView(jLDisciplinas);

        jButton1.setText("Enviar solicitação");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ItemSelection<Alunos> alunoI = (ItemSelection) jCAlunos.getSelectedItem();
        List<ItemSelection<Disciplinas>> disciplinases = jLDisciplinas.getSelectedValuesList();

        Alunos aluno = alunoI.get();
            
        List<Disciplinas> ds = new ArrayList<>();
        for (ItemSelection<Disciplinas> disc : disciplinases) {
            ds.add(disc.get());
        }
       
        aluno.setDisciplinasList(ds);
        
        try {
            MainFrame.ALUNO_CONTROLLER.edit(aluno);

        } catch (Exception ex) {
            Logger.getLogger(UiRelCursoDisciplina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCAlunosActionPerformed
        ItemSelection<Alunos> aluno = (ItemSelection) jCAlunos.getSelectedItem();
        
        List<Disciplinas> disciplinases = aluno.get().getIdCurso().getDisciplinasList();
        Vector<ItemSelection<Disciplinas>> c = new Vector();
        for (Disciplinas disciplinase : disciplinases) {
            c.add(new ItemSelection<>(disciplinase));
        }
        jLDisciplinas.setListData(c);
    }//GEN-LAST:event_jCAlunosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JComboBox jCAlunos;
    javax.swing.JList jLDisciplinas;
    // End of variables declaration//GEN-END:variables
}
