/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.model;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.Disciplinas;
import model.Funcionarios;
import mycustom.CustomFrame;
import mycustom.ItemSelection;
import mycustom.Table;
import ui.MainFrame;

/**
 *
 * @author thomaz
 */
public class UiRelProfessorDisciplina extends CustomFrame {

    /**
     * Creates new form UiRelProfessorDisciplina
     */
    public UiRelProfessorDisciplina() {
        initComponents();
        
        // Fill Func
        List<Funcionarios> funcionarioses = MainFrame.FUNCIONARIO_CONTROLLER.findFuncionariosEntities();
        for (Funcionarios funcionarios : funcionarioses) {
            if( funcionarios.getProfessor() == 1 ) {
                jcProfessor.addItem(new ItemSelection<>(funcionarios)); 
            }
        }
        
        // Fill Disc
        List<Disciplinas> disciplinases2 = MainFrame.DISCIPLINA_CONTROLLER.findDisciplinasEntities();
        for (Disciplinas disciplinas : disciplinases2) {
            jcDisciplina.addItem(new ItemSelection<>(disciplinas)); 
        }
        
        
        tAulas.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                ItemSelection<Funcionarios> f = (ItemSelection<Funcionarios>) jcProfessor.getSelectedItem();
                
                List<Disciplinas> disciplinases = f.get().getDisciplinasList();
                Funcionarios f2 = f.get();
                
                JTable table = (JTable) me.getSource();
                Point p = me.getPoint();
                int row = table.rowAtPoint(p);
                if (me.getClickCount() == 2) {
                    List<Disciplinas> n = new ArrayList<>();
                    int i = 0;

                    for (Disciplinas n1 : disciplinases) {
                        if( i++ != row ) {
                            n.add(n1);
                        } 
                    }
                    
                    f2.setDisciplinasList(n);
                    try {
                        MainFrame.FUNCIONARIO_CONTROLLER.edit(f2);
                    } catch (Exception ex) {
                        Logger.getLogger(UiRelProfessorDisciplina.class.getName()).log(Level.SEVERE, null, ex);
                    }
                                        
                    tAulas.setModel(new Table<>(n, colums));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        jcProfessor = new javax.swing.JComboBox();
        jcDisciplina = new javax.swing.JComboBox();
        javax.swing.JButton jButton1 = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tAulas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Professor");

        jLabel2.setText("Disciplina");

        jcProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcProfessorActionPerformed(evt);
            }
        });

        jcDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcDisciplinaActionPerformed(evt);
            }
        });

        jButton1.setText("Vincular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tAulas.setEnabled(false);
        tAulas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tAulasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tAulas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ItemSelection<Funcionarios> f = (ItemSelection<Funcionarios>) jcProfessor.getSelectedItem();
        ItemSelection<Disciplinas> d = (ItemSelection<Disciplinas>) jcDisciplina.getSelectedItem();
        
        List<Disciplinas> disciplinases = f.get().getDisciplinasList();
        for (Disciplinas disciplinasList : disciplinases) {
            if( d.get().getHorario().equals(disciplinasList.getHorario())
                    && Objects.equals(d.get().getDia(), disciplinasList.getDia()) ) {
                
                JOptionPane.showMessageDialog(rootPane, "Horário não disponível para este professor");
                return;
            }
        }
        
        Funcionarios f2 = f.get();
        List<Disciplinas> d2 = f2.getDisciplinasList();
        d2.add(d.get());
        
        f2.setDisciplinasList(d2);
        
        try {
            MainFrame.FUNCIONARIO_CONTROLLER.edit(f2);
        } catch (Exception ex) {
            Logger.getLogger(UiRelProfessorDisciplina.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        tAulas.setModel(new Table<>(d2, colums));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcDisciplinaActionPerformed

    private void jcProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcProfessorActionPerformed
        ItemSelection<Funcionarios> f = (ItemSelection<Funcionarios>) jcProfessor.getSelectedItem();
        
        tAulas.setModel(new Table<>(f.get().getDisciplinasList(), colums));
    }//GEN-LAST:event_jcProfessorActionPerformed

    private void tAulasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tAulasMouseClicked
    }//GEN-LAST:event_tAulasMouseClicked


    private static final Object[] colums = {"ID", "Disciplina", "Dia/Horário"};
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JComboBox jcDisciplina;
    javax.swing.JComboBox jcProfessor;
    javax.swing.JTable tAulas;
    // End of variables declaration//GEN-END:variables
}
