/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Cursos;
import model.Disciplinas;
import mycustom.ItemSelection;
import mycustom.CustomFrame;
import ui.MainFrame;

/**
 *
 * @author thomaz
 */
public class UiRelCursoDisciplina extends CustomFrame {

    /**
     * Creates new form UiRelCursoDisciplina
     */
    public UiRelCursoDisciplina() {
        initComponents();
        
        List<Cursos> cursos = MainFrame.CURSO_CONTROLLER.findCursosEntities();
        
        for (Cursos curso : cursos) {
            jcCursos.addItem(new ItemSelection<>(curso));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jcCursos = new javax.swing.JComboBox();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        jLDisciplinas = new javax.swing.JList();
        javax.swing.JButton jButton1 = new javax.swing.JButton();
        jLHasDisciplina = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cursos");

        jcCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCursosActionPerformed(evt);
            }
        });

        jLabel2.setText("Disciplinas");

        jScrollPane1.setViewportView(jLDisciplinas);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jcCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLHasDisciplina))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLHasDisciplina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<ItemSelection<Disciplinas>> dL = jLDisciplinas.getSelectedValuesList();
        ItemSelection<Cursos> c = (ItemSelection<Cursos>) jcCursos.getSelectedItem();
        
        Cursos curso = c.get();
            
        List<Disciplinas> ds = new ArrayList<>();
        for (ItemSelection<Disciplinas> disc : dL) {
            ds.add(disc.get());
        }
       
        curso.setDisciplinasList(ds);
        
        try {
            MainFrame.CURSO_CONTROLLER.edit(curso);

        } catch (Exception ex) {
            Logger.getLogger(UiRelCursoDisciplina.class.getName()).log(Level.SEVERE, null, ex);
        }
                  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCursosActionPerformed
        ItemSelection<Cursos> ci = (ItemSelection) jcCursos.getSelectedItem();

        Vector<ItemSelection<Disciplinas>> c = new Vector();
        for (int i = 0; i < ci.get().getDisciplinasList().size(); i++) {
            c.add(new ItemSelection<>(ci.get().getDisciplinasList().get(i)));
        }
        
        jLHasDisciplina.setText(null);
        if( c.isEmpty() ) {
            jLHasDisciplina.setText("Nenhuma disciplina!");
            
            List<Disciplinas> l = MainFrame.DISCIPLINA_CONTROLLER.findDisciplinasEntities();
            for (int i = 0; i <l.size(); i++) {
                c.add(new ItemSelection<>(l.get(i)));
            }
        }
        jLDisciplinas.setListData(c);
    }//GEN-LAST:event_jcCursosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JList jLDisciplinas;
    javax.swing.JLabel jLHasDisciplina;
    javax.swing.JComboBox jcCursos;
    // End of variables declaration//GEN-END:variables
}
